all: cython

cython:
	python setup.py build_ext -i

install: cython
	pip install -e .

clean: cython-clean
	find -name '*.so' | xargs rm -rf
	rm -rf build
	rm -rf *.egg-info
	rm -rf .coverage coverage-report
	find -name '*.pyc' -exec rm {} \;
	find -name '*.so' -exec rm {} \;
	find -name '*.html' -exec rm {} \;

pylint:
	pylint --disable=W0142,W0232,W0212,W0614,W0611,C,R vocrf scripts/*.py

cython-clean:
	(cd vocrf ; find . -name '*.cpp'  -print0 |xargs -0 ack --print0 --files-with-matches '/\* Generated by Cython' |xargs -0 rm -f)
	(cd vocrf ; find . -name '*.c'    -print0 |xargs -0 ack --print0 --files-with-matches '/\* Generated by Cython' |xargs -0 rm -f)
	(cd vocrf ; find . -name '*.html' -print0 |xargs -0 ack --print0 --files-with-matches 'Generated by Cython'     |xargs -0 rm -f)

test: cython
	python vocrf/test/vocrf_tests.py
	python vocrf/test/tree_prox_test.py
	python vocrf/test/spom_test.py
	python -m doctest vocrf/util.py
	python -m doctest vocrf/pos/features.py

.PHONY: langs
langs: \
    data/UD/English \
    data/UD/Spanish \
    data/UD/Basque \
    data/UD/Bulgarian \
    data/UD/Norwegian \
    data/UD/Hindi \
    data/UD/Slovenian \
    data/UD/Basque

# Available languages =
# French Catalan Spanish-AnCora Galician English-ESL Ukrainian Tamil Latin-ITT
# Arabic Czech Portuguese Spanish Indonesian German Hebrew Swedish Persian
# Old_Church_Slavonic Norwegian Latin Latin-PROIEL Japanese-KTC Italian Irish
# Hungarian Greek Gothic Finnish Finnish-FTB Estonian English Bulgarian
# Ancient_Greek Ancient_Greek-PROIEL Slovenian Romanian Polish Hindi Dutch
# Danish Croatian Turkish Kazakh Korean Amharic

data/UD/%:
	mkdir -p data/UD/$(@F)
	(cd data/UD/$(@F) && git clone https://github.com/UniversalDependencies/UD_$(@F).git)
